version: "3"
services:
  web:
    image: enjoy:v1.0
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql://wx:wx@db/wx
      REDIS_URL: redis://redis:6379/0
  #  数据库配置
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 131401
      MYSQL_DATABASE: wx
      MYSQL_USER: wx
      MYSQL_PASSWORD: wx
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
   # 数据库管理界面
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"

  # redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data